config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :user_votes
  resources :options
  resources :polls
  resources :users
  root "main#index"
end

app/models/poll.rb
class Poll < ApplicationRecord
    has_many :options
    accepts_nested_attributes_for :options
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_poll, only: %i[ show edit update destroy ]

  # GET /polls or /polls.json
  def index
    @polls = Poll.all
    
  end

  # GET /polls/1 or /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
    2.times { @poll.options.build }
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls or /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to poll_url(@poll), notice: "Poll was successfully created." }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1 or /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to poll_url(@poll), notice: "Poll was successfully updated." }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1 or /polls/1.json
  def destroy
    @poll.destroy

    respond_to do |format|
      format.html { redirect_to polls_url, notice: "Poll was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def poll_params
      params.require(:poll).permit(:name, options_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.erb
<%= form_with(model: poll, class: "contents") do |form| %>
  <% if poll.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
        <% poll.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.fields_for :options do |option_form| %>
      <div class="my-5">
        <%= option_form.label "Option" %>
        <%= option_form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>
    <% end %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/polls/_poll.html.erb
<div id="<%= dom_id poll %>">
  <h2 class="my-5 font-bold text-2xl">
    <%= poll.name %>
  </h2>

  <div class="flex flex-row gap-4 my-5">
    <% poll.options.each do |option| %>
      <%= form_with(model: UserVote.new, url: user_votes_path, method: :post) do |form| %>
        <%= form.hidden_field :option_id, value: option.id %>
        <%= form.hidden_field :user_id, value: current_user.id %>
        <%= form.submit option.name, class: "rounded-lg py-3 px-5 bg-blue-500 inline-block font-medium text-white" %>
      <% end %>
    <% end %>
  </div>
  
  <div class="flex flex-row gap-4 my-5">
    <% poll.options.each do |option| %>
      <div class="rounded-lg py-3 px-5 border-black border-solid border-2 inline-block font-medium">
        <%= option.name %>
        <%= option.user_votes.count %>
      </div>
    <% end %>
  </div>

  <% if action_name != "show" %>
    <%= link_to "Show this poll", poll, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this poll', edit_poll_path(poll), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/polls/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing poll</h1>

  <%= render "form", poll: @poll %>

  <%= link_to "Show this poll", @poll, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to polls", polls_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/polls/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Polls</h1>
    <%= link_to 'New poll', new_poll_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="polls" class="min-w-full">
    <%= render @polls %>
  </div>
</div>

app/views/polls/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New poll</h1>

  <%= render "form", poll: @poll %>

  <%= link_to 'Back to polls', polls_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/polls/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @poll %>

    <%= link_to 'Edit this poll', edit_poll_path(@poll), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this poll', poll_path(@poll), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to polls', polls_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>